functions:
  createNotes:
    events:
      - http:
          method: post
          path: notes
    handler: handler.createNotes
#    role: LambdaAccessRole
  exportsLogs:
    events:
      - http:
          method: get
          path: exportsLogs
    handler: handler.exportLogs
#    role: LambdaAccessRole
  getNoteById:
    events:
      - http:
          method: get
          path: notes/{id}
    handler: handler.getNotesById
#plugins:
#  - serverless-offline
provider:
  environment:
    APP_NAME: My Notes App
    APP_STAGE: ${opt:stage,self:provider.stage}
    SERVICE_NAME: Notes Service
  iamRoleStatements:
    - Action:
        - s3:*
      Effect: Allow
      Resource: "*"
    - Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:GetLogEvents
        - logs:CreateExportTask
      Effect: Allow
      Resource: "*"
  name: aws
  region: us-east-1
  runtime: nodejs12.x
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dev-function-mysupply-backup1
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    BucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket: dev-function-mysupply-backup1
        PolicyDocument:
         Statement:
          - Action: s3:GetBucketAcl
            Effect: Allow
            Resource: arn:aws:s3:::dev-function-mysupply-backup1
            Principal:
              Service: logs.us-east-1.amazonaws.com
          - Action: s3:PutObject
            Effect: Allow
            Resource: arn:aws:s3:::dev-function-mysupply-backup1/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
            Principal:
              Service: logs.us-east-1.amazonaws.com
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: dev-function-mysupply-backup
service: notes
